accounts:
  - name: validator
    coins: ["200000000smpl"]
  - name: bob
    coins: ["100000000smpl"]
  - name: joe
    coins: ["10000smpl"]
validator:
  name: my_validator
  staked: "100000000smpl"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
